### PR TITLE
AWS interface for context has changed slightly

### PR DESCRIPTION
**Pull request by greylurk**
According to Amazon's docs, the context object has a memory_limit_in_mb attribute, but not a memory_limit attribute.  Is this possibly an outdated interface?

http://docs.aws.amazon.com/lambda/latest/dg/python-context-object.html

### CODE REVIEW

**Comment by ethantkoenig** [comment]
Good catch! Could you remove the old `memory_limit` attribute while you're at it? Otherwise LGTM.

**Comment by greylurk** [comment]
I could, but that would break backwards compatibility.  Just want to make sure you're ok with that.

**Comment by ethantkoenig** [comment]
I'm okay with breaking backwards compatibility, since if your Lambda function uses `context.memory_limit`, it will break when it runs in AWS anyways.

**Comment by greylurk** [comment]
Here's the update. Makes the net change a lot cleaner too.

**Pull request merged**
